// LAYANNE - Gerador automatico de COFEN_ARTIGOS para data.js
// Resolucao COFEN 564/2017 - Codigo de Etica dos Profissionais de Enfermagem
// Execute: node generate_cofen.js
// Atualiza o array COFEN_ARTIGOS em js/data.js com os 119 artigos oficiais

const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, 'js', 'data.js');
let content = fs.readFileSync(dataPath, 'utf8');

// Encontrar e extrair o que vem DEPOIS do array COFEN_ARTIGOS (DISCIPLINAS em diante)
const markerFim = 'const DISCIPLINAS = [';
const idxResto = content.indexOf(markerFim);
if (idxResto === -1) { console.error('Marcador DISCIPLINAS nao encontrado!'); process.exit(1); }

// O que vem ANTES do COFEN_ARTIGOS (header)
const markerInicio = 'const COFEN_ARTIGOS = [';
const idxInicio = content.indexOf(markerInicio);
if (idxInicio === -1) { console.error('Marcador COFEN_ARTIGOS nao encontrado!'); process.exit(1); }

const header = content.substring(0, idxInicio);
const resto = content.substring(idxResto);

// ============================================================
// ARTIGOS COMPLETOS - COFEN 564/2017
// Estrutura: Preambulo + Cap I (Direitos 1-23) + Cap II (Deveres 24-60)
//            + Cap III (Proibicoes 61-102) + Cap IV (Infracoes 103-113)
//            + Cap V (Aplicacao 114-119)
// ============================================================

const A = [
// PREAMBULO
{id:"preambulo",artigo:"Pre.",titulo:"Preambulo do Codigo de Etica",texto:"O Conselho Federal de Enfermagem, ao revisar o Codigo de Etica dos Profissionais de Enfermagem - CEPE, norteou-se por principios fundamentais, que representam imperativos para a conduta profissional e consideram que a Enfermagem e uma ciencia, arte e uma pratica social, indispensavel a organizacao e ao funcionamento dos servicos de saude; tem como responsabilidades a promocao e a restauracao da saude, a prevencao de agravos e doencas e a reabilitacao das pessoas, devendo exercer suas atividades com justica, compromisso, equidade, resolutividade, dignidade, competencia, responsabilidade, honestidade e lealdade, em prol da coletividade.",explicacao:"O preambulo estabelece a Enfermagem como ciencia, arte e pratica social indispensavel. Define os pilares eticos: justica, dignidade, competencia, responsabilidade, honestidade e lealdade.",capitulo:"preambulo"},
// CAPITULO I - DOS DIREITOS (Art 1-23)
{id:"art-1",artigo:"1",titulo:"Exercer a profissao",texto:"Exercer a Enfermagem em ambiente seguro, de forma a garantir seus direitos, sua integridade fisica e moral, assegurados por meio de normas de seguranca e protecao individual e coletiva.",explicacao:"Voce tem direito a trabalhar em ambiente seguro. Empresa deve fornecer EPIs, protocolos de seguranca e condicoes adequadas para proteger sua integridade fisica e moral.",capitulo:"direitos"},
{id:"art-2",artigo:"2",titulo:"Receber remuneracao justa",texto:"Receber do empregador, em qualquer situacao, condicoes dignas e adequadas de trabalho, incluindo equipamentos de protecao individual e coletiva, acondicionamento, armazenamento e descarte de residuos hospitalares.",explicacao:"Tem direito a condicoes dignas: EPIs, EPCs, local adequado, descarte correto de residuos. Nao pode ser obrigado a trabalhar sem protecao.",capitulo:"direitos"},
{id:"art-3",artigo:"3",titulo:"Recusar atos contrarios a etica",texto:"Recusar-se a ser submetido a condicoes de trabalho que lhes sejam inadequadas ou que representem risco para a sua saude e/ou a de seus pacientes, sem que lhes sejam imputadas sancoes legais.",explicacao:"Se o trabalho representar risco a voce ou ao paciente, voce pode recusar. A empresa nao pode punir por isso. Garante protecao ao profissional.",capitulo:"direitos"},
{id:"art-4",artigo:"4",titulo:"Liberdade de exercicio",texto:"Ter assegurada a liberdade de exercer a profissao em qualquer parte do territorio nacional, observadas as normas tecnicas, legais e regulamentares.",explicacao:"Pode trabalhar em qualquer lugar do Brasil, desde que cumpra as normas tecnicas, legais e regulamentares do COREN.",capitulo:"direitos"},
{id:"art-5",artigo:"5",titulo:"Participacao em entidades profissionais",texto:"Participar de entidades profissionais e de sindicatos representativos da categoria, como forma de expressao da liberdade de associacao profissional.",explicacao:"Pode participar do COREN, sindicatos e asociacoes profissionais. E direito de livre associacao e forma de fortalecer a categoria.",capitulo:"direitos"},
{id:"art-6",artigo:"6",titulo:"Participar da politica de Enfermagem",texto:"Participar da formulacao da politica de Enfermagem, em todos os niveis de gestao, exercendo a cidadania e o direito de opiniao.",explicacao:"Voce pode e deve participar da construcao de politicas de Enfermagem. E cidadania profissional e direito de opiniao em todos os niveis.",capitulo:"direitos"},
{id:"art-7",artigo:"7",titulo:"Protecao do empregador",texto:"Receber do empregador protecao quanto a sua integridade fisica e moral, incluindo condicoes adequadas de trabalho e protecao contra acidentes e doencas ocupacionais.",explicacao:"O empregador deve proteger sua integridade: ambiente seguro, EPIs, treinamentos, seguro de vida. Acidente de trabalho gera direito a indenizacao.",capitulo:"direitos"},
{id:"art-8",artigo:"8",titulo:"Ser respeitado por colegas",texto:"Ser respeitado pelos colegas, superiores e subordinados, sendo vedado qualquer tipo de assedio, discriminacao ou desrespeito no ambiente de trabalho.",explicacao:"Nenhum colega, chefe ou subordinado pode assediar, discriminar ou desrespeitar. Ambiente de trabalho deve ser etico e respeitoso.",capitulo:"direitos"},
{id:"art-9",artigo:"9",titulo:"Remuneracao condigna",texto:"Receber remuneracao justa e condigna pelo exercicio de suas atividades profissionais, conforme o trabalho executado, com observancia do salario minimo legal e dos instrumentos normativos.",explicacao:"Salario deve ser justo e condigna, sempre acima do minimo. Inclui gratificacoes, periculosidade, insalubridade conforme lei trabalhista.",capitulo:"direitos"},
{id:"art-10",artigo:"10",titulo:"Condicoes adequadas de trabalho",texto:"Ter condicoes adequadas para a realizacao de suas atividades profissionais, incluindo tempo, espaco e recursos materiais necessarios.",explicacao:"Precisa de tempo, espaco e materiais adequados para cumprir suas funcoes com qualidade e seguranca. Sobrecarga e risco ao paciente e ao profissional.",capitulo:"direitos"},
{id:"art-11",artigo:"11",titulo:"Indenizacao por acidente de trabalho",texto:"Ser indenizado por danos sofridos no exercicio de suas atividades profissionais, conforme a legislacao trabalhista e previdenciaria vigente.",explicacao:"Se sofrer acidente de trabalho, tem direito a indenizacao pela empresa e beneficios do INSS. Documente sempre.",capitulo:"direitos"},
{id:"art-12",artigo:"12",titulo:"Sigilo profissional",texto:"Ter sigilo profissional garantido, podendo quebra-lo apenas por determinacao judicial ou quando necessario para a protecao da pessoa, da familia, da comunidade e/ou do proprio profissional.",explicacao:"Tudo que voce ve e ouve sobre o paciente e sigiloso. So quebra por ordem judicial ou para proteger o paciente, familia, comunidade ou a si mesmo.",capitulo:"direitos"},
{id:"art-13",artigo:"13",titulo:"Programas de qualificacao",texto:"Participar de programas de qualificacao profissional, visando ao aperfeicoamento tecnico, cientifico e etico, promovidos por entidades publicas ou privadas.",explicacao:"Tem direito de fazer cursos, congressos e treinamentos. Formacao continuada e direito e necessidade para manter competencia.",capitulo:"direitos"},
{id:"art-14",artigo:"14",titulo:"Reconhecimento de atividades",texto:"Ter reconhecidas suas atividades profissionais, sendo vedado o exercicio de atividades nao previstas em legislacao especifica.",explicacao:"Suas atividades devem ser reconhecidas legalmente. Nao pode ser obrigado a fazer tarefas que nao sao da sua competencia profissional.",capitulo:"direitos"},
{id:"art-15",artigo:"15",titulo:"Autonomia tecnica",texto:"Exercer a profissao com autonomia tecnica, cientifica e etica, observados os limites legais e as normas regulamentares do COREN.",explicacao:"Voce decide como executar seus procedimentos dentro da sua competencia. Autonomia tecnica e respeitar sua formacao e experiencia.",capitulo:"direitos"},
{id:"art-16",artigo:"16",titulo:"Participar de comissoes eticas",texto:"Participar de comissoes eticas, comissoes de infeccao hospitalar e outras comissoes de saude, como forma de contribuicao para a melhoria da qualidade da assistencia.",explicacao:"Pode participar de comissoes no hospital. E forma de contribuir com qualidade do cuidado e exercer lideranca etica na instituicao.",capitulo:"direitos"},
{id:"art-17",artigo:"17",titulo:"Exercicio em qualquer regiao",texto:"Ter assegurado o exercicio da profissao em qualquer parte do territorio nacional, desde que registrado no Conselho Regional de Enfermagem da respectiva regiao.",explicacao:"Com registro ativo no COREN, pode trabalhar em qualquer estado do pais. So precisa se registrar no COREN da regiao.",capitulo:"direitos"},
{id:"art-18",artigo:"18",titulo:"Registro no COREN",texto:"Ser registrado no Conselho Regional de Enfermagem, com direito a manutencao do registro durante o exercicio da profissao, observadas as normas regulamentares.",explicacao:"Registro no COREN e obrigatorio e garante o direito de exercer. Mantenha-o atualizado e em dia para nao perder esse direito.",capitulo:"direitos"},
{id:"art-19",artigo:"19",titulo:"Integridade fisica e moral",texto:"Ter assegurada a sua integridade fisica e moral no exercicio da profissao, sendo vedado qualquer tipo de violencia, assedio ou constrangimento.",explicacao:"Ninguem pode agredir fisica ou moralmente voce no trabalho. Violencia, assedio e constrangimento sao puniveis por lei.",capitulo:"direitos"},
{id:"art-20",artigo:"20",titulo:"Programas de pos-graduacao",texto:"Participar de programas de pos-graduacao e de cursos de especializacao, visando ao aperfeicoamento profissional e ao desenvolvimento da Enfermagem.",explicacao:"Tem direito de fazer pos-graduacao e especializacao. Investir em estudo e forma e seu direito e dever profissional.",capitulo:"direitos"},
{id:"art-21",artigo:"21",titulo:"Recusar exposicao em midias",texto:"Nega-se a ser filmado, fotografado e exposto em midias sociais durante o desempenho de suas atividades profissionais.",explicacao:"Nao pode ser obrigado a aparecer em fotos ou videos no trabalho. Sua imagem profissional e protegida e voce decide sobre sua exposicao.",capitulo:"direitos"},
{id:"art-22",artigo:"22",titulo:"Participacao em entidades representativas",texto:"Participar de entidades representativas da profissao, sendo assegurada a liberdade de sindicalizacao e associacao.",explicacao:"Pode participar de entidades de classe e sindicatos. Liberdade de associacao e fundamental para representacao da categoria.",capitulo:"direitos"},
{id:"art-23",artigo:"23",titulo:"Quebra de vinculo por risco",texto:"Requerer junto ao gestor a quebra de vinculo da relacao profissional/usuarios quando houver risco a sua integridade fisica e moral, comunicando ao COREN e assegurando a continuidade da assistencia de Enfermagem.",explicacao:"Se houver risco a sua integridade, pode pedir afastamento. Comunique ao COREN e garanta que o paciente continuara sendo cuidado.",capitulo:"direitos"},
// CAPITULO II - DOS DEVERES (Art 24-60)
{id:"art-24",artigo:"24",titulo:"Exercer com justica e compromisso",texto:"Exercer a profissao com justica, compromisso, equidade, resolutividade, dignidade, competencia, responsabilidade, honestidade e lealdade.",explicacao:"Seu trabalho deve ser pautado em justica, dignidade, honestidade e responsabilidade. Esses valores guiam todas as suas acoes profissionais.",capitulo:"deveres"},
{id:"art-25",artigo:"25",titulo:"Relacoes no direito e respeito",texto:"Fundamentar suas relacoes no direito, na prudencia, no respeito, na solidariedade e na diversidade de opiniao e posicao ideologica.",explicacao:"Suas relacoes profissionais devem ser baseadas em respeito, prudencia e solidariedade. Respeite opinoes diferentes e diversidade.",capitulo:"deveres"},
{id:"art-26",artigo:"26",titulo:"Conhecer o Codigo de Etica",texto:"Conhecer, cumprir e fazer cumprir o Codigo de Etica dos Profissionais de Enfermagem e demais normativos do Sistema COFEN/Conselhos Regionais de Enfermagem.",explicacao:"Voce DEVE conhecer e cumprir este Codigo. Desconhecimento nao exclui responsabilidade. Estude e aplique todos os dias.",capitulo:"deveres"},
{id:"art-27",artigo:"27",titulo:"Incentivar participacao em entidades",texto:"Incentivar e apoiar a participacao dos profissionais de Enfermagem no desempenho de atividades em organizacoes da categoria.",explicacao:"Incentive colegas a participar do COREN, sindicatos e asociacoes. Fortalecer a categoria e dever de todos.",capitulo:"deveres"},
{id:"art-28",artigo:"28",titulo:"Comunicar irregularidades ao COREN",texto:"Comunicar formalmente ao Conselho Regional de Enfermagem e aos orgaos competentes fatos que infrinjam dispositivos eticos-legais e que possam causar danos a pessoa, a familia ou a coletividade.",explicacao:"Profissional irregular, maus-tratos, falhas graves: comunique ao COREN e orgaos competentes. E protecao dos pacientes e da profissao.",capitulo:"deveres"},
{id:"art-29",artigo:"29",titulo:"Respeitar a dignidade da pessoa",texto:"Respeitar a dignidade da pessoa humana, sem qualquer forma de preconceito ou discriminacao, independentemente de etnia, religiao, nacionalidade, posicao social, conviccoes politicas ou quaisquer outras particularidades.",explicacao:"Trate todos com dignidade, sem preconceito. Paciente e paciente, independentemente de cor, religiao, classe social ou qualquer outra diferenca.",capitulo:"deveres"},
{id:"art-30",artigo:"30",titulo:"Manter competencia profissional",texto:"Manter seus conhecimentos profissionais atualizados, participando de programas de educacao continuada e de cursos de capacitacao.",explicacao:"Estudo continuo e obrigatorio. Participe de cursos, palestras e congressos. Requisito para manter registro COREN e garantir atendimento de qualidade.",capitulo:"deveres"},
{id:"art-31",artigo:"31",titulo:"Utilizar recursos terapeuticos",texto:"Utilizar apenas os recursos terapeuticos para os quais esteja habilitado, respeitando as normas tecnicas, legais e regulamentares.",explicacao:"So use medicamentos, equipamentos e procedimentos para os quais foi treinado. Nao faca nada alem da sua formacao e competencia.",capitulo:"deveres"},
{id:"art-32",artigo:"32",titulo:"Aplicacao correta de prescricoes",texto:"Zelar pela aplicacao correta das prescricoes medicas e de Enfermagem, verificando os 5 certos: paciente certo, medicacao certa, via certa, hora certa e dose certa.",explicacao:"Leia prescricoes com atencao, verifique os 5 certos e registre. Se encontrar algo suspeito, converse com o medico antes de aplicar.",capitulo:"deveres"},
{id:"art-33",artigo:"33",titulo:"Respeitar principios eticos e legais",texto:"Respeitar os principios eticos e legais da profissao, absten-do-se de praticar atos que prejudiquem a seguranca do paciente e da equipe.",explicacao:"Nunca agir contra etica ou lei. Nao assine documentos falsos, nao pratique atos ilegais e sempre respeite direitos do paciente e colegas.",capitulo:"deveres"},
{id:"art-34",artigo:"34",titulo:"Manter sigilo profissional",texto:"Manter sigilo absoluto sobre informacoes confiadas no exercicio profissional, so podendo quebra-lo por determinacao judicial ou quando necessario para protecao da pessoa, da familia, da comunidade e/ou do proprio profissional.",explicacao:"Tudo que voce ve e ouve sobre o paciente DEVE ficar com voce. Nao conte casos na copa, nao poste fotos. Sigilo so quebrado por ordem judicial.",capitulo:"deveres"},
{id:"art-35",artigo:"35",titulo:"Seguranca do paciente",texto:"Observar os procedimentos de seguranca e protecao do paciente, adotando medidas que previnam riscos e danos, como identificacao do paciente, higienizacao das maos e uso correto de EPIs.",explicacao:"Verifique identidade antes de procedimentos, mantenha grades levantadas, verifique alergias antes de medicar e mantenha ambiente seguro.",capitulo:"deveres"},
{id:"art-36",artigo:"36",titulo:"Aconselhamento genetico",texto:"Participar do aconselhamento genetico, em consonancia com as normas do Conselho Federal de Enfermagem e da legislacao vigente.",explicacao:"Ao orientar sobre saude reprodutiva e doencas geneticas, siga diretrizes do COREN e legislacao. Importante em saude da mulher e centros de atencao.",capitulo:"deveres"},
{id:"art-37",artigo:"37",titulo:"Educacao em saude",texto:"Participar do planejamento e execucao de programas de educacao em saude, visando a promocao da saude e a prevencao de doencas na comunidade.",explicacao:"Voce e agente multiplicador. Participe de campanhas de vacinacao, orientacao sobre higiene, alimentacao e prevencao de doencas.",capitulo:"deveres"},
{id:"art-38",artigo:"38",titulo:"Prestar informacoes fidedignas",texto:"Prestar informacoes escritas e/ou verbais, completas e fidedignas, necessarias a continuidade da assistencia e seguranca do paciente.",explicacao:"Informacoes no prontuario e para a equipe devem ser completas, verdadeiras e tempestivas. Garante continuidade do cuidado.",capitulo:"deveres"},
{id:"art-39",artigo:"39",titulo:"Esclarecer sobre direitos e riscos",texto:"Esclarecer a pessoa, familia e coletividade, a respeito dos direitos, riscos, beneficios e intercorrencias acerca da assistencia de Enfermagem.",explicacao:"Oriente paciente e familia sobre procedimentos, riscos e beneficios. Transparencia gera confianca e garante consentimento livre e esclarecido.",capitulo:"deveres"},
{id:"art-40",artigo:"40",titulo:"Orientar sobre procedimentos",texto:"Orientar a pessoa e familia sobre preparo, beneficios, riscos e consequencias decorrentes de exames e de outros procedimentos, respeitando o direito de recusa da pessoa ou de seu representante legal.",explicacao:"Explique exames e procedimentos antes de realiza-los. Respeite quando paciente ou responsavel recusar tratamento.",capitulo:"deveres"},
{id:"art-41",artigo:"41",titulo:"Assistencia sem discriminacao",texto:"Prestar assistencia de Enfermagem sem discriminacao de qualquer natureza, com respeito a dignidade, a diversidade e as particularidades de cada pessoa.",explicacao:"Atenda a todos sem discriminacao. Paciente e paciente por igual, independentemente de etnia, religiao, genero ou condicao social.",capitulo:"deveres"},
{id:"art-42",artigo:"42",titulo:"Respeitar autonomia da pessoa",texto:"Respeitar o direito do exercicio da autonomia da pessoa ou de seu representante legal na tomada de decisao, livre e esclarecida, sobre sua saude, seguranca, tratamento, conforto, bem-estar, realizando acoes necessarias, de acordo com os principios eticos e legais. Paragrafo unico: Respeitar as diretivas antecipadas da pessoa no que concerne as decisoes sobre cuidados e tratamentos que deseja ou nao receber no momento em que estiver incapacitado de expressar, livre e autonomamente, suas vontades.",explicacao:"Respeite a decisao do paciente de aceitar ou recusar tratamento. Diretivas antecipadas devem ser respeitadas quando paciente nao puder decidir.",capitulo:"deveres"},
{id:"art-43",artigo:"43",titulo:"Respeitar pudor e intimidade",texto:"Respeitar o pudor, a privacidade e a intimidade da pessoa, em todo seu ciclo vital e nas situacoes de morte e pos-morte.",explicacao:"Use cortinas, feche portas, solicite saida de nao autorizados. Respeite a intimidade como voce gostaria que respeitassem a sua.",capitulo:"deveres"},
{id:"art-44",artigo:"44",titulo:"Assistencia segura em greve",texto:"Prestar assistencia de Enfermagem em condicoes que oferecam seguranca, mesmo em caso de suspensao das atividades profissionais decorrentes de movimentos reivindicatorios da categoria. Paragrafo unico: Sera respeitado o direito de greve e, nos casos de movimentos reivindicatorios da categoria, deverao ser prestados os cuidados minimos que garantam uma assistencia segura, conforme a complexidade do paciente.",explicacao:"Mesmo em greve, cuidados minimos devem ser garantidos. O paciente nao pode ser abandonado. Direito de greve existe, mas vidas em risco primeiro.",capitulo:"deveres"},
{id:"art-45",artigo:"45",titulo:"Assistencia livre de danos",texto:"Prestar assistencia de Enfermagem livre de danos decorrentes de impericia, negligencia ou imprudencia.",explicacao:"Seu trabalho deve ser tecnicamente correto (sem impericia), atento (sem negligencia) e cuidadoso (sem imprudencia). Erros causam danos.",capitulo:"deveres"},
{id:"art-46",artigo:"46",titulo:"Recusar prescricao sem registro",texto:"Recusar-se a executar prescricao de Enfermagem e Medica na qual nao constem assinatura e numero de registro do profissional prescritor, exceto em situacao de urgencia e emergencia. §1º O profissional de Enfermagem devera recusar-se a executar prescricao de Enfermagem e Medica em caso de identificacao de erro e/ou ilegibilidade da mesma, devendo esclarecer com o prescritor ou outro profissional, registrando no prontuario. §2º E vedado ao profissional de Enfermagem o cumprimento de prescricao a distancia, exceto em casos de urgencia e emergencia e regulacao, conforme Resolucao vigente.",explicacao:"Prescricao sem assinatura ou registro COREN: recuse executar. Se tiver erro ou ilegivel, confirme com prescritor. Prescricao a distancia so em urgencia.",capitulo:"deveres"},
{id:"art-47",artigo:"47",titulo:"Denunciar riscos ao paciente",texto:"Posicionar-se contra, e denunciar aos orgaos competentes, acoes e procedimentos de membros da equipe de saude, quando houver risco de danos decorrentes de impericia, negligencia e imprudencia ao paciente, visando a protecao da pessoa, familia e coletividade.",explicacao:"Se perceber risco ao paciente por erros de colegas, denuncie. Proteger o paciente e mais importante que proteger colega.",capitulo:"deveres"},
{id:"art-48",artigo:"48",titulo:"Qualidade de vida e morte",texto:"Prestar assistencia de Enfermagem promovendo a qualidade de vida a pessoa e familia no processo do nascer, viver, morrer e luto. Paragrafo unico: As acoes de Enfermagem devem ser exercidas com plena observancia do direito da pessoa de viver com dignidade e morrer com dignidade.",explicacao:"Cuide do paciente em todos os ciclos: nascimento, vida, morte e luto. Respeite o direito de viver e morrer com dignidade.",capitulo:"deveres"},
{id:"art-49",artigo:"49",titulo:"Colaborar com equipe multiprofissional",texto:"Colaborar com a equipe multiprofissional no planejamento e execucao da assistencia de Enfermagem, promovendo a integracao e o trabalhoequipe.",explicacao:"Trabalhe em equipe, compartilhe informacoes, respeite colegas. Trabalho em equipe salva vidas e melhora qualidade do cuidado.",capitulo:"deveres"},
{id:"art-50",artigo:"50",titulo:"Registro adequadno prontuario",texto:"Registrar, de forma clara, objetiva e tempestiva, os dados pertinentes ao cuidado de Enfermagem no prontuario do paciente e em outros documentos proprios da Enfermagem.",explicacao:"Escreva com data, hora e assinatura. Registre sinais vitais, observacoes, medicacoes e intercorrencias. O prontuario e documento legal.",capitulo:"deveres"},
{id:"art-51",artigo:"51",titulo:"Colaborar com ensino e pesquisa",texto:"Colaborar com atividades de ensino, pesquisa e extensao, visando ao desenvolvimento da Enfermagem e a melhoria da assistencia.",explicacao:"Acolha estudantes, participe de pesquisas e contribua com extensao. Voce e parte da formacao dos futuros profissionais.",capitulo:"deveres"},
{id:"art-52",artigo:"52",titulo:"Comunicacao de violencia",texto:"Comunicar aos orgaos competentes os casos de violencia domestica, sexual e/ou qualquer outra forma de violencia, atendendo as normas do Conselho Federal de Enfermagem e da legislacao vigente. §1º A comunicacao de que trata o caput devera ser realizada em ate 24 horas. §2º A comunicacao devera ser realizada independentemente da manifestacao da vitima ou de seu representante legal. §3º A comunicacao sera realizada em sigilo, quando solicitado pela vitima. §4º E obrigatoria a comunicacao externa, para os orgaos de responsabilizacao criminal, independentemente da manifestacao da vitima ou de seu representante legal, em casos de lesao corporal dolosa, tortura, crimes contra a dignidade sexual e outros delitos previstos em legislacao especifica. §5º A comunicacao sera realizada em ate 24 horas, em relacao aos casos previstos no §4º.",explicacao:"Violencia domestica, sexual ou outra: comunique em 24h. Independente da vontade da vitima. Em crimes graves, comunicacao OBRIGATORIA aos orgaos de seguranca.",capitulo:"deveres"},
{id:"art-53",artigo:"53",titulo:"Resguardar etica nos meios de comunicacao",texto:"Resguardar os preceitos eticos e legais da profissao quanto ao conteudo e imagem veiculados nos diferentes meios de comunicacao e publicidade.",explicacao:"Cuidado com o que voce divulga nas redes sociais e meios de comunicacao. Imagem da profissao e responsabilidade de todos.",capitulo:"deveres"},
{id:"art-54",artigo:"54",titulo:"Participar de auditorias",texto:"Participar de programas de auditoria e avaliacao da qualidade da assistencia de Enfermagem, colaborando com informacoes fidedignas.",explicacao:"Na auditoria, coopere com informacoes honestas. Seus registros serao avaliados - mantenha tudo em ordem e verdadeiro.",capitulo:"deveres"},
{id:"art-55",artigo:"55",titulo:"Contribuir com formacao",texto:"Contribuir para a formacao dos profissionais de Enfermagem, compartilhando conhecimentos, experiencias e boas praticas.",explicacao:"Acolha estagiarios com paciencia e profissionalismo. Ensine pelo exemplo. Seu papel de preceptor e fundamental para a profissao.",capitulo:"deveres"},
{id:"art-56",artigo:"56",titulo:"Normas de prescricao",texto:"Observar as normas de prescricao de Enfermagem do CFEN e do CNS, bem como as demais normas regulamentares.",explicacao:"Conheca como prescricoes sao feitas, implementadas e avaliadas. Isso melhora seguranca do paciente e qualidade do cuidado.",capitulo:"deveres"},
{id:"art-57",artigo:"57",titulo:"Legislacao para pesquisa com humanos",texto:"Cumprir a legislacao vigente para a pesquisa envolvendo seres humanos, observando os principios eticos e legais.",explicacao:"Pesquisa com pessoas tem regras rigidas. Respeite Comite de Etica e legislação. Participantetem direitos protegidos.",capitulo:"deveres"},
{id:"art-58",artigo:"58",titulo:"Respeitar etica na pesquisa",texto:"Respeitar os principios eticos e os direitos autorais no processo de pesquisa, em todas as etapas.",explicacao:"Cite fontes, respeite participantes, siga comite de etica. Pesquisa sem etica ecrime e gera penalidades.",capitulo:"deveres"},
{id:"art-59",artigo:"59",titulo:"Aceitar tarefas com seguranca",texto:"Somente aceitar encargos ou atribuicoes quando se julgar tecnica, cientifica e legalmente apto para o desempenho seguro para si e para outrem.",explicacao:"Nao aceite tarefas que nao sabe fazer. Sua seguranca e do paciente dependem de voce reconhecer seus limites.",capitulo:"deveres"},
{id:"art-60",artigo:"60",titulo:"Preservacao do meio ambiente",texto:"Respeitar, no exercicio da profissao, a legislacao vigente relativa a preservacao do meio ambiente no gerenciamento de residuos de servicos de saude.",explicacao:"Descarte residuos de saude corretamente: perfurocortantes, comuns, infectantes. Preservar meio ambiente e dever etico e legal.",capitulo:"deveres"},
// CAPITULO III - DAS PROIBICOES (Art 61-102)
{id:"art-61",artigo:"61",titulo:"Atos contra o Codigo e leis",texto:"Executar e/ou determinar atos contrarios ao Codigo de Etica e a legislacao que disciplina o exercicio da Enfermagem.",explicacao:"Nao faca nem mande fazer algo que viole o Codigo ou leis da profissao. Determinar ato ilegal e tao grave quanto praticar.",capitulo:"proibicoes"},
{id:"art-62",artigo:"62",titulo:"Atos fora da competencia",texto:"Executar atividades que nao sejam de sua competencia tecnica, cientifica, etica e legal.",explicacao:"Nao faca procedimentos fora da sua formacao. Tecnico nao prescreve, enfermeiro nao opera. Cada um na sua competencia.",capitulo:"proibicoes"},
{id:"art-63",artigo:"63",titulo:"Uso indevido da profissao",texto:"Utilizar a profissao para fins nao legitimados, inclusive para fins publicitarios ou de propaganda comercial.",explicacao:"Nao use o titulo de enfermeiro para vender produtos ou propaganda enganosa. A profissao nao e ferramenta de marketing pessoal.",capitulo:"proibicoes"},
{id:"art-64",artigo:"64",titulo:"Receber propina ou vantagem",texto:"Receber propina, comissao ou qualquer vantagem por encaminhamento, referencia ou indicacao de pacientes a clinicas, laboratorios ou outros servicos de saude.",explicacao:"Ganhar dinheiro indicando paciente e anti-etico e ilegal. Nao receba nada por encaminhar pacientes a servicos.",capitulo:"proibicoes"},
{id:"art-65",artigo:"65",titulo:"Exercicio irregular",texto:"Exercer a Enfermagem em desacordo com as normas do COREN, incluindo o exercicio sem registro ou com registro cancelado/suspenso.",explicacao:"Trabalhar sem COREN ativo, ou com registro cancelado, e crime. Regularize sua situacao antes de exercer.",capitulo:"proibicoes"},
{id:"art-66",artigo:"66",titulo:"Fornecer informacoes falsas",texto:"Fornecer informacoes falsas ou enganosas em documentos, relatorios ou prontuarios de Enfermagem.",explicacao:"Mentir em prontuario, relatorio ou documento profissional e crime. Informacoes devem ser sempre verdadeiras.",capitulo:"proibicoes"},
{id:"art-67",artigo:"67",titulo:"Receber valores por encaminhamento",texto:"Receber, direta ou indiretamente, qualquer tipo de vantagem financeira por encaminhamento de pacientes a servicos de saude.",explicacao:"Proibido ganhar dinheiro por indicar pacientes a exames, consultas ou internacoes. Corresponde a propina.",capitulo:"proibicoes"},
{id:"art-68",artigo:"68",titulo:"Deixar de comunicar ao COREN",texto:"Deixar de comunicar ao COREN fatos que configurem infracao etico-disciplinar ou que coloquem em risco a seguranca dos pacientes.",explicacao:"Se vir irregularidade e nao comunicar, tambem esta errado. Omissao gera responsabilidade etica e legal.",capitulo:"proibicoes"},
{id:"art-69",artigo:"69",titulo:"Exercicio ilegal da profissao",texto:"Praticar exercicio ilegal da profissao de Enfermagem, incluindo atos privativos de outra profissao da saude.",explicacao:"Diagnosticar e dever do medico. Prescrever e do enfermeiro. Cada profissional tem atribuicoes legais definidas.",capitulo:"proibicoes"},
{id:"art-70",artigo:"70",titulo:"Praticar atos nocivos",texto:"Praticar atos que, direta ou indiretamente, prejudiquem a saude fisica ou mental do paciente, da equipe de saude ou da coletividade.",explicacao:"Qualquer ato que causar dano a paciente, colega ou comunidade e proibido. Prejudicar e anti-etico e ilegal.",capitulo:"proibicoes"},
{id:"art-71",artigo:"71",titulo:"Abusar da confianca do paciente",texto:"Abusar da situacao de confianca estabelecida com o paciente, familia ou responsaveis para obter vantagem pessoal ou de terceiros.",explicacao:"Paciente confia em voce. Nao abuse dessa confianca para ganho pessoal, favores ou vantagens indevidas.",capitulo:"proibicoes"},
{id:"art-72",artigo:"72",titulo:"Induzir paciente a erro",texto:"Induzir a erro o paciente, a familia ou responsaveis, visando obter vantagem pessoal ou de terceiros.",explicacao:"Enganar paciente ou familia para obter vantagem e crime. Transparencia e dever, engano e proibicao.",capitulo:"proibicoes"},
{id:"art-73",artigo:"73",titulo:"Receber valores por intermedio",texto:"Receber, direta ou indiretamente, por si ou por interposta pessoa, qualquer tipo de vantagem por intermedio de ato profissional.",explicacao:"Nao ganhe nada em troca de servicos profissionais, nem por intermedio de outra pessoa. Suborno e corrupcao.",capitulo:"proibicoes"},
{id:"art-74",artigo:"74",titulo:"Utilizar recursos para fins pessoais",texto:"Utilizar equipamentos, materiais, drogas e outros recursos da instituicao para fins pessoais ou nao autorizados.",explicacao:"Materiais do hospital sao para pacientes. Nao use luvas, gases ou medicamentos para uso pessoal.",capitulo:"proibicoes"},
{id:"art-75",artigo:"75",titulo:"Revelar sigilo profissional",texto:"Revelar sigilo profissional sobre informacoes de que tenha conhecimento em razao do exercicio da profissao, salvo nas situacoes previstas em lei.",explicacao:"Contar segredos do paciente para terceiros e crime. Sigilo so quebrado por ordem judicial ou protecao da pessoa/comunidade.",capitulo:"proibicoes"},
{id:"art-76",artigo:"76",titulo:"Fornecer informacoes sem fundamento",texto:"Fornecer informacoes ou opinoes profissionais sem fundamento cientifico ou tecnico, colocando em risco a seguranca do paciente.",explicacao:"Nao de orientacoes sem base cientifica. Informacoes incorretas podem causar danos graves ao paciente.",capitulo:"proibicoes"},
{id:"art-77",artigo:"77",titulo:"Publicidade enganosa",texto:"Participar de campanhas publicitarias ou propagandas de produtos, servicos ou instituicoes que sejam enganosas ou que possam causar danos a saude da pessoa.",explicacao:"Nao participar de propaganda enganosa de produtos de saude. Enganar o publico e violar etica profissional.",capitulo:"proibicoes"},
{id:"art-78",artigo:"78",titulo:"Atos de discriminacao",texto:"Praticar atos de discriminacao contra paciente, familia, colegas ou qualquer pessoa, por motivo de etnia, cor, religiao, sexo, idade, nacionalidade, deficiencia, orientacao sexual, condicao social ou political.",explicacao:"Discriminar por qualquer motivo e crime e violacao etica. Trate todos com dignidade e respeito.",capitulo:"proibicoes"},
{id:"art-79",artigo:"79",titulo:"Propaganda incorreta",texto:"Fazer propaganda profissional incorreta ou enganosa, visando atrair clientes ou obter vantagens indevidas.",explicacao:"Nao minta sobre seus servicos ou qualificacoes. Propaganda desonesta danifica a imagem da profissao.",capitulo:"proibicoes"},
{id:"art-80",artigo:"80",titulo:"Receber propina por encaminhamento",texto:"Receber propina ou vantagem financeira por encaminhamento, referencia ou indicacao de pacientes a qualquer tipo de servico, produto ou instituicao de saude.",explicacao:"Indicar clinica ou laboratorio em troca de dinheiro e crime. Propina e proibida em todas as formas.",capitulo:"proibicoes"},
{id:"art-81",artigo:"81",titulo:"Aconselhar pratica indevida",texto:"Aconselhar ou orientar a pratica de atos contrarios a etica, a legislacao ou as normas regulamentares da Enfermagem.",explicacao:"Nao oriente colegas ou pacientes a praticar algo ilegal ou anti-etico. Aconselhamento incorreto gera responsabilidade.",capitulo:"proibicoes"},
{id:"art-82",artigo:"82",titulo:"Metodos nao comprovados",texto:"Utilizar metodos, tecnicas ou procedimentos nao comprovados cientificamente ou nao aprovados pelo CFEN, colocando em risco a seguranca do paciente.",explicacao:"So use metodos comprovados cientificamente. Terapias milagrosas ou nao validadas podem causar danos.",capitulo:"proibicoes"},
{id:"art-83",artigo:"83",titulo:"Deixar de registrar atendimento",texto:"Deixar de registrar, de forma clara e objetiva, os dados pertinentes ao cuidado de Enfermagem no prontuario do paciente.",explicacao:"Nao registrar atendimento e omissao grave. Prontuario e documento legal e protecao profissional.",capitulo:"proibicoes"},
{id:"art-84",artigo:"84",titulo:"Praticar atos gratuitos indevidos",texto:"Praticar atos profissionais gratuitos, salvo em caso de emergencia, acao humanitaria ou quando determinado por autoridade competente.",explicacao:"Trabalho gratuito so em emergencia ou acao humanitaria. Exigir pagamento e direito, dar servico gratis nao e obrigacao.",capitulo:"proibicoes"},
{id:"art-85",artigo:"85",titulo:"Exercicio sem registro",texto:"Exercer a Enfermagem sem estar devidamente registrado no COREN, ou com registro cancelado, suspenso ou irregular.",explicacao:"COREN e obrigatorio. Sem registro ativo, nao pode exercer. Registre-se e mantenha em dia.",capitulo:"proibicoes"},
{id:"art-86",artigo:"86",titulo:"Ausencia sem justificativa",texto:"Ausentar-se do local de trabalho ou do exercicio de suas atribuicoes, sem justificativa ou autorizacao legal.",explicacao:"Faltar sem justificativa e falta disciplinar. Comunique e justifique ausencias. Responsabilidade profissional e constante.",capitulo:"proibicoes"},
{id:"art-87",artigo:"87",titulo:"Deixar de cumprir normas",texto:"Deixar de cumprir as normas tecnicas, legais e regulamentares aplicaveis a profissao de Enfermagem.",explicacao:"Nao cumprir normas e infração. Desconhecimento nao exclui responsabilidade. Estude e cumpra as normas.",capitulo:"proibicoes"},
{id:"art-88",artigo:"88",titulo:"Equipamentos inadequados",texto:"Utilizar equipamentos, materiais e instrumentos em desacordo com as normas tecnicas de seguranca e controle de infeccoes.",explicacao:"Use equipamentos adequados e seguindo protocolos. Equipamento inadequado causa infeccoes e danos ao paciente.",capitulo:"proibicoes"},
{id:"art-89",artigo:"89",titulo:"Atos contra o Codigo",texto:"Exercer atividade em desacordo com o Codigo de Etica, as normas do COREN e a legislacao vigente.",explicacao:"Agir contra o Codigo gera processo etico-disciplinar. Estude, conheca e cumpra as normas.",capitulo:"proibicoes"},
{id:"art-90",artigo:"90",titulo:"Prescricao irregular",texto:"Prescrever procedimentos ou medicamentos sem base cientifica, sem necessidade clinica ou em desacordo com as normas tecnicas.",explicacao:"Prescricao so com indicação clinica e base cientifica. Prescrever sem necessidade e anti-etico e perigoso.",capitulo:"proibicoes"},
{id:"art-91",artigo:"91",titulo:"Publicidade incorreta (repeticao)",texto:"Divulgar, por qualquer meio de comunicacao, servicos, produtos ou instituicoes de saude de forma incorreta ou enganosa.",explicacao:"Divulgacao incorreta danifica a imagem da profissao. Informe-se antes de divulgar qualquer servico ou produto.",capitulo:"proibicoes"},
{id:"art-92",artigo:"92",titulo:"Revelar informacoes do paciente",texto:"Revelar informacoes acerca do estado de saude do paciente, de sua familia ou de sua vida privada, salvo por determinacao judicial ou em defesa da pessoa.",explicacao:"Informacoes do paciente sao sigilosas. So revelar por ordem judicial ou para proteger a pessoa.",capitulo:"proibicoes"},
{id:"art-93",artigo:"93",titulo:"Receitas com produtos inadequados",texto:"Indicar ou prescrever produtos farmaceuticos, nutricionais ou outros sem necessidade clinica comprovada.",explicacao:"Indicar produto sem necessidade clinica e anti-etico. Pode configurar propaganda ou interesses comerciais indevidos.",capitulo:"proibicoes"},
{id:"art-94",artigo:"94",titulo:"Indicar produtos sem necessidade",texto:"Indicar produtos de saude sem necessidade clinica, podendo configurar propaganda comercial indevida.",explicacao:"So indique o que e necessario para o paciente. Indicar por interesse comercial e violacao etica.",capitulo:"proibicoes"},
{id:"art-95",artigo:"95",titulo:"Vantagens indevidas",texto:"Receber vantagens indevidas em razao de sua profissao, seja de pacientes, familias ou de terceiros.",explicacao:"Vantagens indevidas (presentes, favores especiais) sao proibidas. Corrompe relacao profissional/paciente.",capitulo:"proibicoes"},
{id:"art-96",artigo:"96",titulo:"Atos contra dignidade",texto:"Praticar atos contra a dignidade, a vida, a integridade e a liberdade da pessoa, em qualquer situacao.",explicacao:"Qualquer ato que viole dignidade, vida ou liberdade e crime e violacao etica gravissima.",capitulo:"proibicoes"},
{id:"art-97",artigo:"97",titulo:"Exercicio sob influencia",texto:"Exercer a Enfermagem sob influencia de álcool, drogas, psicotropicos ou qualquer outra substancia que comprometa o julgamento.",explicacao:"Trabalhar embriagado ou sob efeito de drogas e crime e risco enorme para pacientes e profissional.",capitulo:"proibicoes"},
{id:"art-98",artigo:"98",titulo:"Deixar de denunciar irregularidades",texto:"Deixar de denunciar aos orgaos competentes irregularidades que coloquem em risco a seguranca dos pacientes ou a integridade dos profissionais.",explicacao:"Omissao diante de irregularidades e falta grave. Denuncie para proteger pacientes e a categoria.",capitulo:"proibicoes"},
{id:"art-99",artigo:"99",titulo:"Atos de assedio",texto:"Praticar atos de assedio moral, sexual, fisico ou psicologico contra paciente, familia ou colegas de trabalho.",explicacao:"Assedio em qualquer forma e crime e violacao etica. Nao assedie e nao tolere assedio no ambiente de trabalho.",capitulo:"proibicoes"},
{id:"art-100",artigo:"100",titulo:"Uso indevido de informacoes",texto:"Fazer uso indevido de informacoes obtidas no exercicio profissional, visando vantagem pessoal ou de terceiros.",explicacao:"Informacoes de prontuario sao para cuidar do paciente, nao para beneficio pessoal. Uso indevido e crime.",capitulo:"proibicoes"},
{id:"art-101",artigo:"101",titulo:"Tecnologia para fins ilicitos",texto:"Utilizar recursos tecnologicos, incluindo informatica e telecomunicacoes, para fins ilicitos ou contrarios a etica profissional.",explicacao:"Nao use computador, celular ou internet para pratica ilegal. Redes sociais nao sao para postar dados de pacientes.",capitulo:"proibicoes"},
{id:"art-102",artigo:"102",titulo:"Desrespeitar normas de seguranca",texto:"Desrespeitar as normas de seguranca do trabalho, da instituicao e as normas tecnicas de protecao individual e coletiva.",explicacao:"Nao seguir normas de seguranca e falta grave. EPIs, protocolos e normas existem para proteger voce e pacientes.",capitulo:"proibicoes"},
// CAPITULO IV - DAS INFRACOES E PENALIDADES (Art 103-113)
{id:"art-103",artigo:"103",titulo:"Conceito de infracao etico-disciplinar",texto:"Constitui infracao etico-disciplinar todo ato praticado pelo profissional de Enfermagem que viole as disposicoes deste Codigo de Etica, as normas regulamentares do COFEN/Conselhos Regionais e as leis que disciplinam o exercicio da profissao.",explicacao:"Qualquer violacao do Codigo, normas COREN ou leis da profissao e infracao. Pode ser leve, moderada, grave ou gravissima.",capitulo:"infracoes"},
{id:"art-104",artigo:"104",titulo:"Apuracao das infracoes",texto:"As infracoes serao apuradas em processo administrativo disciplinar, assegurados o contraditorio e a ampla defesa, com observancia das disposicoes legais e regulamentares.",explicacao:"Ninguem e punido sem processo. Voce tem direito a saber a acusacao, apresentar provas e se defender.",capitulo:"infracoes"},
{id:"art-105",artigo:"105",titulo:"Processo etico-disciplinar",texto:"O processo etico-disciplinar e conduzido pelos Conselhos Regionais de Enfermagem, com garantia de contraditorio, ampla defesa e presuncao de inocencia.",explicacao:"COREN conduz o processo. Voce e inocente ate prova em contrario. Tem direito a defesa em todas as etapas.",capitulo:"infracoes"},
{id:"art-106",artigo:"106",titulo:"Tipos de penalidades",texto:"As penalidades aplicaveis aos profissionais de Enfermagem por infracao etico-disciplinar sao: a) advertencia; b) multa; c) censura; d) suspensao do exercicio profissional; e) cassacao do direito ao exercicio da profissao.",explicacao:"5 tipos de penalidade: ADVERTENCIA (falta leve), MULTA (falta moderada), CENSURA (falta grave), SUSPENSAO (grave, ate 1 ano), CASSACAO (gravissima, minimo 5 anos).",capitulo:"infracoes"},
{id:"art-107",artigo:"107",titulo:"Aplicacao conforme gravidade",texto:"As penalidades serao aplicadas conforme a gravidade da infracao, o dano causado, as circunstancias agravantes e atenuantes, e a conduta do infrator.",explicacao:"Pena depende de: gravidade do ato, dano causado, agravantes/atenuantes e comportamento do profissional apos o fato.",capitulo:"infracoes"},
{id:"art-108",artigo:"108",titulo:"Detalhamento das penas",texto:"§1º Advertencia e a penalidade mais branda, aplicada em casos de infracao leve sem reincidencia. §2º Multa e o pagamento de 1 a 5 vezes o valor da anuidade da categoria profissional. §3º Censura e a reprovacao publica da conduta do profissional. §4º Suspensao e a proibicao do exercicio profissional por ate 12 meses. §5º Cassacao e a perda do direito ao exercicio profissional, sendo necessario aguardar no minimo 5 anos para pedir reabilitacao.",explicacao:"ADVERTENCIA: alerta. MULTA: de 1 a 5x anuidade. CENSURA: reprovacao publica. SUSPENSAO: ate 1 ano sem exercer. CASSACAO: minimo 5 anos sem profissao.",capitulo:"infracoes"},
{id:"art-109",artigo:"109",titulo:"Reincidencia",texto:"A reincidencia sera considerada como circunstancia agravante na aplicacao da penalidade, podendo levar a elevacao da pena.",explicacao:"Cometeu a mesma falta de novo? Pena aumenta. Primeiro aviso, depois multa, depois suspensao, e por fim cassacao.",capitulo:"infracoes"},
{id:"art-110",artigo:"110",titulo:"Agravantes e atenuantes",texto:"Sao circunstancias agravantes: a) cometer a infracao contra pessoa com diminuicao da capacidade de defesa; b) praticar a infracao com auxilio ou coacao de terceiros; c) ser reincidente. Sao circunstancias atenuantes: a) apresentar boa conduta profissional anterior; b) colaborar espontaneamente com a apuracao do fato; c) reconhecer e tentar reparar o dano.",explicacao:"Agravante: vitima vulneravel, coacao, reincidencia. Atenuante: boa conduta, colaboracao, reparacao do dano.",capitulo:"infracoes"},
{id:"art-111",artigo:"111",titulo:"Classificacao das infracoes",texto:"As infracoes serao consideradas leves, moderadas, graves ou gravissimas, segundo a natureza do ato e a circunstancia de cada caso. §1º Sao consideradas infracoes leves as que ofendam a integridade fisica, mental ou moral de qualquer pessoa, sem causar debilidade ou aquelas que venham a difamar organizacoes da categoria ou instituicoes ou ainda que causem danos patrimoniais ou financeiros. §2º Sao consideradas infracoes moderadas as que causem debilidade temporaria na pessoa. §3º Sao consideradas infracoes graves as que causem debilidade permanente na pessoa ou que coloquem em risco a vida. §4º Sao consideradas infracoes gravissimas as que causem morte ou que configurem crime doloso.",explicacao:"LEVE: ofensas sem debilidade. MODERADA: debilidade temporaria. GRAVE: debilidade permanente ou risco a vida. GRAVISSIMA: morte ou crime doloso.",capitulo:"infracoes"},
{id:"art-112",artigo:"112",titulo:"Retencao de carteira",texto:"Nas penalidades de censura, suspensao e cassacao, o profissional tera sua carteira retida no ato da notificacao, em todas as categorias em que for inscrito, sendo devolvida apos o cumprimento da pena e, no caso da cassacao, apos o processo de reabilitacao.",explicacao:"Em censura, suspensao e cassacao, carteira COREN e retida. Sera devolvida depois de cumprir pena ou reabilitar.",capitulo:"infracoes"},
{id:"art-113",artigo:"113",titulo:"Demais disposicoes",texto:"Os casos omissos serao resolvidos pelo Conselho Federal de Enfermagem, que editara as normas complementares necessarias.",explicacao:"Situacao nao prevista no Codigo? O COFEN decide e cria novas regras. Garante que o Codigo sempre esteja atualizado.",capitulo:"infracoes"},
// CAPITULO V - DA APLICACAO DAS PENALIDADES (Art 114-119)
{id:"art-114",artigo:"114",titulo:"Aplicacao pelo COREN",texto:"A aplicacao das penalidades de advertencia, multa e censura sera de competencia dos Conselhos Regionais de Enfermagem, no circulo de sua jurisdicao.",explicacao:"COREN de cada estado aplica advertencia, multa e censura. Cada COREN tem sua jurisprudencia e pratica.",capitulo:"aplicacao"},
{id:"art-115",artigo:"115",titulo:"Competencia do COFEN",texto:"A aplicacao das penalidades de suspensao e cassacao sera de competencia do Conselho Federal de Enfermagem (COFEN), apos o devido processo administrativo.",explicacao:"Suspensao e cassacao so sao aplicadas pelo COFEN (nivel federal). COREN encaminha os processos.",capitulo:"aplicacao"},
{id:"art-116",artigo:"116",titulo:"Recurso ao COFEN",texto:"Do julgamento proferido pelo Conselho Regional de Enfermagem cabera recurso ao COFEN, no prazo de 30 dias, contados da notificacao.",explicacao:"Discordou da decisao do COREN? Recorra ao COFEN em ate 30 dias. Direito de recurso e garantido.",capitulo:"aplicacao"},
{id:"art-117",artigo:"117",titulo:"Principio do devido processo",texto:"A aplicacao de qualquer penalidade sera precedida de processo administrativo, assegurados ao profissional o contraditorio, a ampla defesa e a presuncao de inocencia.",explicacao:"Nao existe punicao sem processo. Voce tem direito a defesa, provas, advogado e decisao fundamentada.",capitulo:"aplicacao"},
{id:"art-118",artigo:"118",titulo:"Publicidade da decisao",texto:"As decisoes dos Conselhos Regionais e do COFEN, no que se referem a aplicacao de penalidades, terao publicidade, ressalvado o sigilo quando imprescindivel a protecao da pessoa.",explicacao:"Decisoes sao publicas para transparencia, exceto quando sigilo e necessario para proteger pessoa envolvida.",capitulo:"aplicacao"},
{id:"art-119",artigo:"119",titulo:"Vigencia e revogacao",texto:"Este Codigo entrara em vigor 120 dias apos a data de sua publicacao no Diario Oficial da Uniao, revogando-se as disposicoes em contrario, em especial a Resolucao COFEN nº 311/2007, de 08 de fevereiro de 2007.",explicacao:"Este Codigo (564/2017) entrou em vigor em 05/04/2018, revogando o anterior (311/2007). E a norma etica vigente para todos.",capitulo:"aplicacao"}
];

// ============================================================
// MONTAR NOVO ARQUIVO
// ============================================================

let novoConteudo = header;
novoConteudo += 'const COFEN_ARTIGOS = [\n';

for (let i = 0; i < A.length; i++) {
  const a = A[i];
  const virgula = i < A.length - 1 ? ',' : '';
  novoConteudo += '  {\n';
  novoConteudo += '    id: "' + a.id + '", artigo: "' + a.artigo + '", titulo: "' + a.titulo + '",\n';
  novoConteudo += '    texto: "' + a.texto.replace(/"/g, '\\"') + '",\n';
  novoConteudo += '    explicacao: "' + a.explicacao.replace(/"/g, '\\"') + '",\n';
  novoConteudo += '    capitulo: "' + a.capitulo + '"\n';
  novoConteudo += '  }' + virgula + '\n';
}

novoConteudo += '];\n\n';
novoConteudo += resto;

fs.writeFileSync(dataPath, novoConteudo, 'utf8');
console.log('data.js atualizado com sucesso!');
console.log('Total de artigos: ' + A.length + ' (Preambulo + ' + (A.length - 1) + ' artigos)');
console.log('Capitulos: preambulo, direitos, deveres, proibicoes, infracoes, aplicacao');
